[ALLI-6920] OnkiLightEnrichment: enrich records with available WGS 84 data
NatLibFi/RecordManager-Finna pull request #10
Opened 2022-03-11 09:14 UTC by kouralex

2022-03-11 09:15 UTC, kouralex commented on src/RecordManager/Base/Enrichment/NominatimGeocoder.php
> -                    if (!empty($this->solrCenterField)) {
Tässä kohtaa tarkistus on ollut erilainen, halutaanko tämän mukaan edelleen tarkistaa?

2022-03-11 09:19 UTC, kouralex commented on src/RecordManager/Base/Enrichment/OnkiLightEnrichment.php
> +            'lat' => $item['http://www.w3.org/2003/01/geo/wgs84_pos#lat'] ?? null,
Teknisenä huomiona sanottakoon, että jos Skosmoksen päässä joskus muutetaan JSON-LD-datan tulostusta, ei tämä välttämättä toimi (on mahdollista, että tulee prefiksattuna silloin). Helpointa lukemisessa olisi käyttää oikeaa JSON-LD-kirjastoa, mutta en halunnut tämän vuoksi lisätä uutta riippuvuutta.

2022-03-11 10:38 UTC, EreMaijala requested changes

2022-03-11 10:38 UTC, EreMaijala commented on src/RecordManager/Base/Enrichment/OnkiLightEnrichment.php
> +        if (isset($settings['solr_location_field'])) {
`$settings` on tuntematon tässä

2022-03-11 10:38 UTC, EreMaijala commented on src/RecordManager/Base/Enrichment/NominatimGeocoder.php
> +        $center = !empty($solrArray[$this->solrCenterField]) ?
Huomioitava, että `$this->solrCenterField` voi olla myös tyhjä (=ei käytössä).

2022-03-11 10:38 UTC, EreMaijala commented on src/RecordManager/Base/Enrichment/NominatimGeocoder.php
> -                    if (!empty($this->solrCenterField)) {
Tässä tarkistetaan, onko kenttä käytössä Solr:ssa, ei sisältöä. Eli eri tarkistus kuin se, onko kentällä sisältöä. Jos ei ole käytössä, ei tarvitse tehdä muita tarkistuksia, mutta muuten pitää tehdä molemmat.

2022-03-11 10:38 UTC, EreMaijala commented on src/RecordManager/Base/Enrichment/OnkiLightEnrichment.php
> +                $solrArray[$this->solrLocationField] = array_merge(
Yksinkertaisemmin: `$solrArray[$this->solrLocationField][] = $locItem['wkt'];`

2022-03-11 10:38 UTC, EreMaijala commented on src/RecordManager/Base/Enrichment/OnkiLightEnrichment.php
> +            if (!empty($wktLocationStr)
Ei tarvitse empty-funktiota, riittää `if ($wktLocationStr && ...)`

2022-03-11 10:38 UTC, EreMaijala commented on src/RecordManager/Base/Enrichment/OnkiLightEnrichment.php
> +                && preg_match('/^POINT\s*\(/', $wktLocationStr)
Laittaisin muodon tarkistuksen ja muun käsittelyn vielä omaan metodiin, esim. processLocationWkt, joka hoitaa validoinnin, muotoilun ym. ja välittää sitten tuloksen processLocationItem:lle. Tässä preg_match:ssa voisi myös saman tien poimia koordinaatit, niin ei tarvitsisi explode+substr:ää.

2022-03-11 10:38 UTC, EreMaijala commented on src/RecordManager/Base/Enrichment/OnkiLightEnrichment.php
> +     * Process item WGS 84 location data and add that information to solrArray
"item" ei liene merkityksellinen, joten tämä voisi olla vain "Process WGS 84 location data..." ja metodi processLocationWgs84.

2022-03-11 10:38 UTC, EreMaijala commented on src/RecordManager/Base/Enrichment/OnkiLightEnrichment.php
> +            'lat' => $item['http://www.w3.org/2003/01/geo/wgs84_pos#lat'] ?? null,
Olisiko helppo tarkistaa molemmat vaihtoehdot?

2022-03-11 10:38 UTC, EreMaijala commented on src/RecordManager/Base/Enrichment/OnkiLightEnrichment.php
> +        $wktItem = [
Nämä voisi ottaa yksinkertaisesti muuttujiin `$lat` ja `$lon`. Arrayn voi sitten tehdä vasta, jos sitä tarvitaan, ja muu koodi on selkeämpää.

2022-03-11 10:38 UTC, EreMaijala commented on src/RecordManager/Base/Enrichment/OnkiLightEnrichment.php
> +        if (!isset($solrArray[$this->solrCenterField])) {
`$this->solrCenterField` voi olla myös tyhjä, tarkistettava.

2022-03-11 10:38 UTC, EreMaijala commented on src/RecordManager/Base/Enrichment/NominatimGeocoder.php
>      protected function enrichLocations($locations, &$solrArray)
Base-nimiavaruuden muutokset RecordManager-repoon.

2022-03-16 11:34 UTC, kouralex commented
Closing this in favor of https://github.com/NatLibFi/RecordManager/pull/105.

2022-03-16 11:34 UTC, closed without merging