Add mimeType and format to online urls
NatLibFi/RecordManager-Finna pull request #14
Opened 2022-05-17 14:13 UTC by LuomaJuha

Takes into account QDC and LRMI records at the moment.

2022-05-18 12:35 UTC, EreMaijala requested changes
Varmaan kannattaisi tehdä tämä kaikille nyt saman tien, että voi sitten luottaa siihen, että tieto on saatavissa indeksissä.

2022-05-18 12:35 UTC, EreMaijala commented on src/RecordManager/Finna/Record/FileHelperTrait.php
> +    protected function getMimeTypeWithExtension(string $extension): string
Nimeäisin tämän `getMimeTypeFromExtension`

2022-05-18 12:35 UTC, EreMaijala commented on src/RecordManager/Finna/Record/FileHelperTrait.php
> +    protected function getURLExtension(string $url): string
Nimeäisin tämän `getFileExtensionFromUrl`

2022-05-18 12:35 UTC, EreMaijala commented on src/RecordManager/Finna/Record/FileHelperTrait.php
> +            '/^http(s)?:\/\/.*\.([a-zA-Z0-9]{3,4})$/',
Tämä ei oikein toimi, jos on vaikka kuvailtu pelkkä domain (https://www.example.com => com). Ainakin ehtona pitäisi olla, että URL:ssa on jotain muutakin ennen pistettä, mutta ehkä lisäksi lista mahdollisesti sallituista arvoista? Muuten esim. jotain.aspx on varmaan ihan oikein ja sille voi löytyä mime-tyyppikin, mutta ei se sisällöstä kerro.

2022-05-18 12:35 UTC, EreMaijala commented on src/RecordManager/Finna/Record/FileHelperTrait.php
> +     * Get type from the mime or empty.
'Get content type from MIME type.' 'or empty' pois, on jo selitetty return:n kohdalla.

2022-05-18 12:35 UTC, EreMaijala commented on src/RecordManager/Finna/Record/FileHelperTrait.php
> +    protected function getTypeFromMime(string $mimeType): string
`getContentTypeFromMimeType`

2022-05-18 12:35 UTC, EreMaijala commented on src/RecordManager/Finna/Record/FileHelperTrait.php
> +     * @return string Found type or empty.
'Type or empty string if not available.'

2022-05-18 12:35 UTC, EreMaijala commented on src/RecordManager/Finna/Record/FileHelperTrait.php
> +        return $this->mimetypeDetector->detectMimeTypeFromPath($path) ?? '';
Näissä pitäisi tarkistaa, että mimetypeDetector on asetettu ja heittää poikkeus, jos ei ole.

2022-05-18 13:30 UTC, LuomaJuha commented
Voin kyllä tehdä myös lidolle oman onlineUrls keräilyn.

2022-05-18 13:32 UTC, LuomaJuha commented on src/RecordManager/Finna/Record/FileHelperTrait.php
> +            '/^http(s)?:\/\/.*\.([a-zA-Z0-9]{3,4})$/',
hmm, vois olla joo parempi. Pitääpi vähän miettiä miten muotoilisi paremmin.

2022-05-19 11:06 UTC, EreMaijala requested changes
Ihme homma, GH sekoilee jotain..

2022-05-19 11:07 UTC, EreMaijala commented
Marcista tulee myös, eikö?

2022-06-03 09:56 UTC, LuomaJuha commented on src/RecordManager/Finna/Record/FileHelperTrait.php
> +        return $this->mimetypeDetector->detectMimeTypeFromPath($path) ?? '';
Yritin laittaa tohon isset tarkastusta, mutta psalm ei oikein tykännyt siitä vaan väitti että se pitäisi laittaa jo constructorissa.

2022-06-03 09:56 UTC, LuomaJuha commented on src/RecordManager/Finna/Record/FileHelperTrait.php
> +        return $this->mimetypeDetector->detectMimeTypeFromPath($path) ?? '';
Yritin laittaa tohon isset tarkastusta, mutta psalm ei oikein tykännyt siitä vaan väitti että se pitäisi laittaa jo constructorissa.

2022-11-07 08:09 UTC, LuomaJuha commented
Closing this one to simplify it alot.

2022-11-07 08:09 UTC, closed without merging