Add possibility to override access restrictions
NatLibFi/RecordManager-Finna pull request #15
Opened 2022-05-31 13:46 UTC by LuomaJuha

Add support for restricted_str in records

2022-06-01 08:50 UTC, EreMaijala commented
@LuomaJuha Needs to be added also to the upstream AbstractRecord class so that all record classes get support for it.

2022-06-01 12:14 UTC, LuomaJuha commented
@EreMaijala Added a support for the field restricted_str to ::toSolrArray so other declarations can be removed from datasources.ini.

2022-06-01 16:36 UTC, EreMaijala requested changes

2022-06-01 16:36 UTC, EreMaijala commented on src/RecordManager/Finna/Record/Marc.php
> +        if ($overrideRestriction = $this->getDriverParam('accessRestrictions', '')) {
Now that we have the basic check in the parent class, I think it would make sense to change this to something like:
```
if ($restrictions = parent::getAccessRestrictions()) {
    return $restrictions;
}
```

2022-08-22 07:35 UTC, LuomaJuha commented
This seems obsolete now.

2022-08-22 07:35 UTC, closed without merging

2022-08-23 05:55 UTC, EreMaijala commented
@LuomaJuha Sorry, I completely forgot this one while adding the other!

2022-08-23 06:46 UTC, LuomaJuha commented
@EreMaijala no worries! This is still in here if the other formats also require the same access checks.