[ALLI-7630] QDC: improve search and publication daterange handling
NatLibFi/RecordManager-Finna pull request #20
Opened 2022-10-24 14:31 UTC by LuomaJuha

2022-10-31 11:24 UTC, EreMaijala requested changes

2022-10-31 11:24 UTC, EreMaijala commented on src/RecordManager/Finna/Record/QdcRecordTrait.php
>      protected function getPublicationDateRange()
Muutetaan nimi `getPublicationDateRanges`. Ja paluuarvo tässä ratkaisussa voisi olla aina array, ei tuolla null:lla ole enää virkaa.

2022-10-31 11:26 UTC, LuomaJuha commented on src/RecordManager/Finna/Record/QdcRecordTrait.php
>      protected function getPublicationDateRange()
Kuulostaa hyvältä

2022-11-03 10:42 UTC, EreMaijala approved these changes

2022-11-03 10:42 UTC, merged