[ALLI-7693] EAD3: Improve year range handling in record title
NatLibFi/RecordManager-Finna pull request #23
Opened 2022-11-29 12:08 UTC by rajaro

2022-12-05 11:10 UTC, rajaro commented
@EreMaijala en nyt jostain syystä saa lisättyä review pyyntöä tähän, mutta tän voi katselmoida

2022-12-08 07:53 UTC, EreMaijala requested changes
1. Kun nuo testitapaukset ovat kovin samankaltaisia, voisi tehdä ennemmin niin, että olisi yksi fixture, jossa olisi placeholder vuosivälille, johon sitten testissä vaihdetaan halutun muotoinen päivämäärä ja luodaan siitä tietue. Sitten voisi käyttää dataProvideria ja tehdä vain yhden testin, joka testaa kaikki tapaukset. 

2. Testeissä olisi hyvä olla myös tapaus, jossa päivämäärää ei löydy nimekkeestä valmiina.

2022-12-08 07:53 UTC, EreMaijala commented on tests/RecordManagerTest/Finna/Record/Ead3Test.php
> +        $mdash = html_entity_decode('&#x2014;', ENT_NOQUOTES, 'UTF-8');
`$mdash` turha?

2023-02-08 14:38 UTC, rajaro commented
@EreMaijala tätä voi tsekata

2023-02-24 09:14 UTC, EreMaijala requested changes

2023-02-24 09:14 UTC, EreMaijala commented on tests/RecordManagerTest/Finna/Record/Ead3Test.php
> +        $titleReg = '/>(.*)<\/unittitle>/';
Pitäisi varmaan olla `(.*?)` ettei korvaa liian laajasti.

2023-02-24 09:14 UTC, EreMaijala commented on tests/RecordManagerTest/Finna/Record/Ead3Test.php
> +        yield 'test dash' => [
Lisää vielä vastaava ilman välejä tyyliin '1932-1935'.

2023-02-24 15:18 UTC, EreMaijala approved these changes

2023-02-24 15:18 UTC, merged