[ALLI-7630] Parse Qdc dateranges more precisely
NatLibFi/RecordManager-Finna pull request #24
Opened 2022-11-30 14:56 UTC by LuomaJuha

2022-12-08 08:08 UTC, EreMaijala requested changes
Mä pitäisin selkeämpänä tehdä koko homma yhdellä regexp:llä samaan tapaan kuin #23:ssa (ja mukaan sekä ndash että mdash).

2022-12-08 08:08 UTC, EreMaijala commented on src/RecordManager/Finna/Record/DateSupportTrait.php
> +            if (intval($result['startYear']) > intval($result['endYear'])) {
Castataan int:ksi. Sama asia, mutta kielen konstruktiona potentiaalisesti nopeampi kuin funktio.

2022-12-09 11:47 UTC, LuomaJuha commented on src/RecordManager/Finna/Record/DateSupportTrait.php
> +            if (intval($result['startYear']) > intval($result['endYear'])) {
jepulis! Laitetaas muokaten

2022-12-14 11:16 UTC, EreMaijala requested changes

2022-12-14 11:16 UTC, EreMaijala commented on src/RecordManager/Finna/Record/DateSupportTrait.php
> +            '/([-]{0,1}\b\d{4})\b[-]{0,1}\d{0,2}\b[-]{0,1}\b\d{0,2}\b/',
Korvaa `{0,1}` kysymysmerkillä `?`, niin on vähän yksinkertaisempi.

2022-12-14 11:16 UTC, EreMaijala commented on tests/RecordManagerTest/Finna/Record/QdcTest.php
> +     * @dataProvider getDateRangeResults
Ei tee mitään data providerilla, kun on vain yksi datasetti.

2022-12-14 11:16 UTC, EreMaijala commented on tests/fixtures/Finna/record/qdc_dateranges.xml
> +    <!-- Valid dates -->
Testitapauksiin voisi lisätä ainakin välimerkittömän päivämäärän ja päivämäärävälin tyyliin `20221214` ja `20221212-20221214`.

2022-12-14 12:40 UTC, LuomaJuha commented on tests/fixtures/Finna/record/qdc_dateranges.xml
> +    <!-- Valid dates -->
lisäsin loppuun seuraavat kolme:

    <date>20221212-20221214</date>
    <date>20221210</date>
    <date>2 028----00 05</date>

2022-12-21 07:50 UTC, EreMaijala requested changes

2022-12-21 07:50 UTC, EreMaijala commented on tests/RecordManagerTest/Finna/Record/QdcTest.php
> +        $expected
outo rivitys, laita:

```
$expected = [
    'jotain',
];
```

2022-12-21 07:50 UTC, EreMaijala commented on src/RecordManager/Finna/Record/DateSupportTrait.php
> +            '/([-]?\b\d{4})\b[-]?\d{0,2}\b[-]?\b\d{0,2}\b/',
Vielä ottaisin hakasulut pois viivan ympäriltä, pitäisi mun mielestä toimia niinkin: `'/(-?\b\d{4})\b-?\d{0,2}\b-?\b\d{0,2}\b/'`

2022-12-21 07:50 UTC, EreMaijala commented on tests/RecordManagerTest/Finna/Record/QdcTest.php
> +                '[3010-01-01 TO 3010-12-31]'
Lisää testitapauksiin vielä sellainen, jonka range on miinukselta plussalle.

2022-12-21 08:50 UTC, LuomaJuha commented on src/RecordManager/Finna/Record/DateSupportTrait.php
> +            '/([-]?\b\d{4})\b[-]?\d{0,2}\b[-]?\b\d{0,2}\b/',
No niimpäs näytti toimivan.

2022-12-21 09:04 UTC, EreMaijala commented on tests/RecordManagerTest/Finna/Record/QdcTest.php
> +                '[3010-01-01 TO 3010-12-31]'
Eiku onhan siellä jo.

2022-12-21 09:07 UTC, EreMaijala approved these changes

2022-12-21 09:10 UTC, merged