[ALLI-7839] EAD3: Fix appending year range to titles
NatLibFi/RecordManager-Finna pull request #28
Opened 2023-03-01 13:28 UTC by LuomaJuha

If any results are found, then do not append the year range into a title.

Sets the fixture title to its original state after running tests. Otherwise it shows up as modified file in git.

2023-03-01 13:35 UTC, LuomaJuha commented
Into a draft for now. An idea popped into my head.

2023-03-02 06:00 UTC, EreMaijala commented
@LuomaJuha Let's add createRecordFromString (that createRecord can also call) and modify the records on the fly so that no changes on disk are needed.

2023-03-02 10:16 UTC, LuomaJuha commented
Seems like this needs more tests to cover all the occurences.

2023-03-03 11:58 UTC, EreMaijala requested changes

2023-03-03 11:58 UTC, EreMaijala commented on src/RecordManager/Finna/Record/Ead3.php
> +         * noyearexists = If any year is found from the title then do not add
Näihin voisi laittaa välit tai väliviivat. `no-year-exists` olisi helpompi lukea.

2023-03-03 11:58 UTC, EreMaijala commented on src/RecordManager/Finna/Record/Ead3.php
> +         * nomatchesexists = If all of the given years in unitDateRange are
`no-matches-exist`, ilman loppu-ässää.

2023-03-03 12:05 UTC, EreMaijala commented on src/RecordManager/Finna/Record/Ead3.php
> +         * noyearexists = If any year is found from the title then do not add
Itse asiassa alaviiva taitaa olla käytössä, voisi suosia sitä.

2023-03-03 12:06 UTC, EreMaijala commented on src/RecordManager/Finna/Record/Ead3.php
> +         * noyearexists = If any year is found from the title then do not add
Tai camelCase, miten vain näyttää paremmalta.

2023-03-06 14:12 UTC, LuomaJuha commented on src/RecordManager/Finna/Record/Ead3.php
> +         * noyearexists = If any year is found from the title then do not add
alaviivat oli jotenkin mukavammat.

2023-03-08 11:09 UTC, EreMaijala requested changes

2023-03-08 11:09 UTC, EreMaijala commented on src/RecordManager/Finna/Record/Ead3.php
> +         * no_match_exist = If any of the given years in unitDateRange are
Tässä, kun on match yksikössä, pitäisi olla se loppu-s..

2023-03-08 15:29 UTC, LuomaJuha commented on src/RecordManager/Finna/Record/Ead3.php
> +         * no_match_exist = If any of the given years in unitDateRange are
ei jumpe, englanti...

2023-03-09 09:03 UTC, EreMaijala approved these changes

2023-03-09 09:03 UTC, merged