[ALLI-7952] Fix ltr as rtl year after rtl text
NatLibFi/RecordManager-Finna pull request #31
Opened 2023-03-31 13:30 UTC by siiriylonen

2023-04-03 07:20 UTC, siiriylonen commented
En voi lisätä reviewer, että kai tämä nyt meni oikeaan paikkaan? @EreMaijala

2023-04-04 07:12 UTC, EreMaijala requested changes
html_entity_decode on itse asiassa vanhentunut tapa, kun nykyään voi laittaa suoraan UNICODE-merkin näin: `"\u{200E}"`. Käytetään mieluummin uutta tapaa.

2023-04-04 08:09 UTC, EreMaijala requested changes

2023-04-04 08:09 UTC, EreMaijala commented on src/RecordManager/Finna/Record/Ead3.php
> +            $yearRangeStr = "\u{200E}" . " ($yearRangeStr)";
Laita samaan stringiin, niin ei tarvitse turhaan yhdistää kahta. Voisi ehkä lisätä yläpuolelle myös kommentin tyyliin `// Append with LTR mark first to ensure correct text direction`

2023-04-04 08:09 UTC, EreMaijala commented on tests/RecordManagerTest/Finna/Record/Ead3Test.php
> +        $ltr = html_entity_decode('&#8206;');
Tässä vielä vanha.

2023-04-05 16:50 UTC, EreMaijala approved these changes

2023-04-05 16:52 UTC, merged