[FINNA-1114] Index identifying places to geographic fields
NatLibFi/RecordManager-Finna pull request #49
Opened 2023-10-18 08:04 UTC by siiriylonen

2023-10-18 08:06 UTC, siiriylonen commented
@EreMaijala review pyyntö..

2023-10-18 11:15 UTC, EreMaijala requested changes

2023-10-18 11:15 UTC, EreMaijala commented on src/RecordManager/Base/Record/Lido.php
> +    /**
Base-luokkien muutokset NatLibFi/RecordManager:iin.

2023-10-18 11:15 UTC, EreMaijala commented on src/RecordManager/Base/Record/Lido.php
> +    protected function getIdentifyingPlaces(): array
Minusta getRepositoryLocations tms. olisi kuvaavampi tälle.

2023-10-19 10:46 UTC, siiriylonen commented
Tässä nyt ei pitäisi tulla virheitä (näyttivät johtuvan kun poistin ne base muutokset), mutta täällä vaan ei sitä re-run all jobs.

2023-10-26 08:39 UTC, LuomaJuha commented
@siiriylonen Kannattaa ottaa uusi dev, kun oli ristiriita tuossa funktion nimessä.

2023-11-13 12:05 UTC, EreMaijala requested changes

2023-11-13 12:05 UTC, EreMaijala commented on src/RecordManager/Finna/Record/Lido.php
> +        foreach (
Lisää testi (tai laajenna olemassaolevaa), joka tarkistaa tämän toiminnan.

2023-11-13 12:05 UTC, EreMaijala commented on src/RecordManager/Finna/Record/Lido.php
> +                $types = ['prt', 'kiinteistötunnus'];
Nämä luokan muuttujiin, siellä alussa on paljon muitakin samantyyppisiä.

2023-11-13 12:05 UTC, EreMaijala commented on tests/fixtures/Finna/record/musketti2.xml
> +                        <repositoryLocation>
Voisi olla kaksi repositoryLocation:ia vaikka nimillä "Repository location 1" ja "Repository location 2", niin varmistuu, että molemmat tulevat mukaan.

2023-11-15 06:36 UTC, EreMaijala approved these changes

2023-11-15 06:36 UTC, merged