[FINNA-1184] EAD3: Fix wrong time information when date includes unknown characters
NatLibFi/RecordManager-Finna pull request #52
Opened 2023-11-15 12:09 UTC by siiriylonen

2023-11-15 12:47 UTC, siiriylonen commented
@EreMaijala review

2023-11-16 08:21 UTC, EreMaijala requested changes

2023-11-16 08:21 UTC, EreMaijala commented on src/RecordManager/Finna/Record/Ead3.php
> +                            || !str_contains($normal, 'uuuu')
Pitäisikö tässä olla `&&` eikä `||`?

2023-11-16 08:21 UTC, EreMaijala commented on src/RecordManager/Finna/Record/Ead3.php
> +                    $result[] = $parsedDate = $this->parseDateRange($normal);
Turha kai sitä mahdollisesti tyhjää arvoa on `$result[]`:iin laittaa?

2023-11-16 08:21 UTC, EreMaijala commented on src/RecordManager/Finna/Record/Ead3.php
> +                            if (
Nämä if:t voisi yhdistää samaan.

2023-11-16 08:21 UTC, EreMaijala commented on tests/fixtures/Finna/record/yksa.xml
> +    <unitdate normal="1917-XX-XX">1917</unitdate>
Lisää testit myös niille, joissa on xxxx tai uuuu.

2023-11-17 05:40 UTC, EreMaijala requested changes

2023-11-17 05:40 UTC, EreMaijala commented on src/RecordManager/Finna/Record/Ead3.php
> +                            (!str_contains($normal, 'xxxx') && !str_contains($normal, 'uuuu'))
Tällä rivillä ympäröivät sulut tarpeettomat, hämmentävät suotta.

2023-11-17 06:55 UTC, EreMaijala approved these changes

2023-11-17 06:56 UTC, merged