[FINNA-1796] MARC: Fix authority topic ids that have a source
NatLibFi/RecordManager-Finna pull request #64
Opened 2024-03-22 06:28 UTC by siiriylonen

2024-04-12 09:49 UTC, EreMaijala requested changes

2024-04-12 09:49 UTC, EreMaijala commented on src/RecordManager/Finna/Record/Marc.php
> +                if ($regex && preg_match($regex, $id)) {
This check should be part of the previous if statement so that getThesaurusId doesn't get called at all if its result won't be used.

2024-04-12 09:49 UTC, EreMaijala commented on src/RecordManager/Finna/Record/Marc.php
> +                // Do not prepend source in front of authority ids
.. in front of *known* authority ids (i.e. already prefixed)

2024-04-12 13:29 UTC, siiriylonen commented on src/RecordManager/Finna/Record/Marc.php
> +                if ($regex && preg_match($regex, $id)) {
I'm not sure if I understood part of previous if how, but now it's not called if not needed?

2024-04-15 13:35 UTC, EreMaijala requested changes

2024-04-15 13:35 UTC, EreMaijala commented on src/RecordManager/Finna/Record/Marc.php
> +                } elseif ($srcId = $this->getThesaurusId($field)) {
Since the if branch above returns, this doesn't need `else`.

2024-04-16 06:45 UTC, EreMaijala approved these changes

2024-04-16 06:46 UTC, merged