[FINNA-2060] Fix repository location indexing
NatLibFi/RecordManager-Finna pull request #65
Opened 2024-04-05 11:35 UTC by siiriylonen

2024-04-16 08:35 UTC, siiriylonen commented
Tämän testit pitäisi olla ok, mutta se \Base muutos nyt ei vielä ollutkaan siellä.

Muokkasin tässä myös testitietoja esimerkkitietueen kaltaiseksi.

2024-04-22 08:33 UTC, EreMaijala commented
@siiriylonen Uusin dev mergetty RecordManager-reposta, eli voit mergetä nyt tännekin uusimman RecordManager-Finna:n dev:n.

2024-04-24 07:40 UTC, EreMaijala requested changes

2024-04-24 07:40 UTC, EreMaijala commented on tests/fixtures/Finna/record/musketti2.xml
> -                            <namePlaceSet>
Eikö nämä kannattaisi jättää, jotta voi varmistua, että niitä ei oteta mukaan?

2024-04-24 07:56 UTC, EreMaijala approved these changes

2024-04-24 07:56 UTC, merged