[FINNA-2009] Marc: Index performers
NatLibFi/RecordManager-Finna pull request #74
Opened 2024-11-19 14:28 UTC by rajaro

2024-11-28 11:31 UTC, EreMaijala requested changes
Lisää myös testitapaus, jossa on kaksi ehjää 382-kenttää ja tapaus, jossa jälkimmäisessä 382-kentässä on vaikka vain n-osakenttä.

2024-11-28 11:31 UTC, EreMaijala commented on tests/fixtures/Finna/record/marc-performers.xml
> +</collection>
Rivinvaihto loppuun

2024-11-28 11:31 UTC, EreMaijala commented on src/RecordManager/Finna/Record/Marc.php
> +                    $data['performer_str_mv'][array_key_last($data['performer_str_mv'])]
Tämän pitäisi selviytyä myös tilanteesta, jossa ei ole edeltävää osakenttää a, b, d, tai p. Lisäksi pitäisi käsitellä kerralla yksittäinen 382-kenttä. Nyt voisi käydä niin, että n tai e lisätään edelliseen 382-kenttään.

2024-11-28 11:31 UTC, EreMaijala commented on src/RecordManager/Finna/Record/Marc.php
> +                    $data['performer_total_int'] = $subfield['data'];
Tämän pitäisi olla _mv, koska voi olla useampi kokoonpano.

2024-12-04 11:53 UTC, rajaro commented
@EreMaijala Muutokset tehty. Tein siis `performer_total_int` kentästä `performer_total_int_mv` ja sitä käsitellään array:na, mutta jotta sain toimimaan testailussa niin vaati solr:in schema muutosta sen verran, että piti lisätä 
`<dynamicField name="*_int_mv" type="int"/>` riville `multiValued="true"`

2024-12-04 12:26 UTC, EreMaijala commented
@rajaro Oho, korjaan skeeman.

2024-12-04 12:40 UTC, EreMaijala approved these changes

2024-12-04 12:40 UTC, merged